### ISSUE TITLE
Create the user dashboard

### ISSUE THREAD

**Issue by PrinkalDhingra** [opencodeiiita/SkillSync-Frontend#11]
In this exciting task you have to build the user dashboard for a registered user.
features include:  1)side menubar containing settings, edit profile etc options.
2) Use piecharts and graphs to show how active the user was in the particular month and in how many events he participated in.
3)option for log out
4)edit profile option

A reference image is provided . You are free to show your creativity.
![dashboard_image](https://github.com/user-attachments/assets/f42b5afc-92a1-4e32-9598-d9e39c3bf8d6)

Make use of react , MaterialUI , tailwindcss to make a beautiful and responsive design.

Time-48hrs

Note: comment to claim the issue .Also provide a screenshot the dashboard you created in your pr description.

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by Vardaan-02** [comment]
Do you guys even read before merging the request @PrinkalDhingra

**Comment by Vardaan-02** [comment]
this man added css in index.css  how am i supposed to fix this .

he didn't even made classes he added css to tags . 

![Screenshot From 2024-12-19 00-57-26](https://github.com/user-attachments/assets/56f1fcb8-2ad1-4f1c-949c-1f9c498336c5)

**Comment by Debankur04** [comment]
Hello @Vardaan-02 I am the person behind this pull, and i appreciate your concern but I have strictly worked on the user dashboard and not the signin page, and if you look closely this css is being used in signin and not the dashboard. So I don't think I am the one responsible here. Hope it clears some doubts Thank you.

**Comment by Vardaan-02** [comment]
![Screenshot From 2024-12-19 01-10-43](https://github.com/user-attachments/assets/ceb045a7-87ec-49a1-b3d6-6db3f627667e)

Bhai this is indes.css file. This will affect changes in the whole project and to add ghee in aag you have added css diretly to button tag

**Comment by Vardaan-02** [comment]
so you are not the one who changed the index.css.  i am sorry for the miscommunication

**Comment by Vardaan-02** [comment]
![Screenshot From 2024-12-19 01-10-43](https://github.com/user-attachments/assets/ed4956e2-ad5b-4963-944d-abb6d05a9f66)
![Screenshot From 2024-12-19 01-15-42](https://github.com/user-attachments/assets/1e768288-ccd9-416d-a067-8d32dcecfb7e)
this man 
![Screenshot From 2024-12-19 01-15-56](https://github.com/user-attachments/assets/088208d5-dc7e-4db8-bf3f-ad78826a40f1)

This man added css in index.css file and that too on button tag . 

when i asked for clarification he said it was not him but he did add that css in that screenshot.
