### ISSUE TITLE
Create an about us page 

### ISSUE THREAD

**Issue by PrinkalDhingra** [opencodeiiita/SkillSync-Frontend#16]
Hola contributors

In this exciting task you have to create an about us page for the skillSync website .
Features required - What SkillSync is all about , its main goal , our top sponsors and a review slider from the user which include star ratings and a short review. Remember the review slider is important and should be responsive. A reference is provided is provided below for the slider. Feel free to show your creativity.

![Screenshot 2024-12-17 221457](https://github.com/user-attachments/assets/666f03ae-befa-4dd9-a726-d2ccaaea8df5)

Make use of react , tailwindcss , MaterialUI. 

Time - 48hrs

Note-Comment to claim the issue.

**Comment by SHARUKA-2005** [comment]
claim

**Comment by dark-dev2475** [comment]
assign it to me

**Comment by PriyamJChakrabarty** [comment]
@PrinkalDhingra the assignment has been removed......can u assign it now?

**Comment by PriyamJChakrabarty** [comment]
claim
