### ISSUE TITLE
Create a Navbar and add a user profile dropdown in the Navbar with links to settings, profile, and logout.

### ISSUE THREAD

**Issue by PrathamJain2601** [opencodeiiita/SkillSync-Frontend#17]
**Issue Title:**  
Add a user profile dropdown in the Navbar with links to settings, profile, and logout  

---

### **Issue Description:**  
Enhance the Navbar by adding a **user profile dropdown menu** that provides quick access to essential user-related links, such as:  
1. **Profile**: Navigates to the user's profile page to view and edit personal details.  
2. **Settings**: Opens the settings page where users can customize preferences.  
3. **Logout**: Logs the user out and redirects them to the login page.  

This dropdown improves user navigation and aligns with modern application design standards.

---

### **Feature Scope:**  
1. **Dropdown Design**  
   - A user avatar (profile picture) or an icon will act as the trigger button.  
   - When clicked, a dropdown menu will appear below the avatar icon.  
   - Menu items include:  
     - **View Profile**  
     - **Settings**  
     - **Logout**  

2. **Links/Routes**  
   - **Profile**: `/profile` route (e.g., User Profile page)  
   - **Settings**: `/settings` route (User preferences page)  
   - **Logout**: Logs out the user by clearing tokens, resetting state, and redirects to `/login`.  

3. **Responsive Behavior**  
   - The dropdown must be fully responsive and appear correctly on mobile, tablet, and desktop views.  

4. **Authentication Integration**  
   - Ensure the dropdown is visible **only when the user is logged in**.  
   - Use the user data fetched from the authentication system to display the profile picture and username.
   - For Now create a dummy.json file which exports an auth object. it should have an isLogin key which is true/false, it tells if user is loggedIn

---

### **Acceptance Criteria:**  
- [ ] User avatar or icon is displayed on the right side of the Navbar.  
- [ ] Clicking the avatar opens a dropdown with three options: **Profile**, **Settings**, and **Logout**.  
- [ ] Links navigate to the correct pages:  
    - **Profile** ➡ `/profile`  
    - **Settings** ➡ `/settings`  
    - **Logout** ➡ Clears user and redirects to `/login`.  
- [ ] Dropdown works seamlessly on all screen sizes (responsive).  
- [ ] Display the user's profile picture dynamically (fallback to default icon if unavailable).  
- [ ] Proper hover and click states for menu items.  

---

### **Technical Notes:**  
- **Tech Stack**:  
   - Create a custom dropdown using Tailwind CSS.  
   - Use Redux for managing authentication state. 

- **Steps to Implement:**  
   1. Add a user avatar component in the Navbar.  
   2. Integrate the dropdown component with proper menu items (`Profile`, `Settings`, and `Logout`).  .  
   3. Implement the **Logout** function to clear tokens (localStorage/cookies) and reset the app state.  
   4. Add routes for Profile (`/profile`) and Settings (`/settings`) pages if they don’t already exist.  
   5. Ensure responsiveness using Tailwind utilities or media queries.

### **Additional Notes:**  
1. Tailwind CSS can be used to build a custom dropdown.  
2. Make sure to include a **default avatar image** if the user does not have a profile picture.  
3. Add hover states and transitions for better UX.  

---

### **Priority:**  
- **High** (essential for user navigation and app usability).  

### **Time Estimate:**  
- **16-20 hours** (includes UI development, authentication integration, and testing).  

---

Would you like further details on implementing this with Tailwind CSS? 🚀

**Comment by PriyamJChakrabarty** [comment]
Claim
