### ISSUE TITLE
Sculpting the Perfect Logo

### ISSUE THREAD

**Issue by vanshdvn2505** [opencodeiiita/SkillSync-Frontend#2]
Create a Logo for SkillSync

SkillSync is a platform that bridges the gap between learners and mentors by fostering skill-sharing and networking. We need a modern, visually appealing logo that aligns with the platform's values of connection, growth, and collaboration.

Maintain a design that is simple, easily recognizable, and versatile across various platforms and sizes. A clutter-free logo will enhance memorability and adaptability.

Requirements:-
1.) Concept: The logo should represent skill-sharing, collaboration, and connectivity.
2.) Style: Minimalistic, modern, and professional.
3.) Choose colors that evoke trust, reliability, and professionalism

Once the logo is created, include the URL (Figma, Canva, or any design tool used) in the design.json file. Refer to the existing example in the file for guidance.

Time: 24 hours.
```json
{
  "project": "SkillSync Logo",
  "design_url": "https://figma.com/file/example-logo"
}
```
Note: No Need to Claim the issue, The Best will get merged in 24 hours, Other may get partial points though,

**Comment by swarupn17** [comment]
Isn't there partial points for closed PRs, considering the effort put into the work?
