### ISSUE TITLE
Combined Issue: Add a Theme Toggle Button and a Logo Redirect to the Navbar

### ISSUE THREAD

**Issue by PrathamJain2601** [opencodeiiita/SkillSync-Frontend#23]
### **Combined Issue: Add a Theme Toggle Button and a Logo Redirect to the Navbar**

---

#### **Issue Description:**  
Enhance the Navbar with the following features:  
1. **Theme Toggle Button**: Allow users to switch between light and dark themes for a personalized and accessible interface.  
2. **Logo Redirect**: Add a clickable logo to the Navbar that redirects users to the homepage or dashboard.

These features aim to improve user experience by providing a customizable interface and easy navigation.

---

#### **Theme Toggle Button**  
1. **Light/Dark Mode Switch**:  
   - Include a toggle button in the Navbar to switch between light and dark themes.  
   - Update the application’s appearance dynamically based on the selected theme.  

2. **Theme Persistence**:  
   - Ensure the selected theme persists across sessions using local storage or user preferences.  

3. **UI Design**:  
   - Use a toggle switch or icon-based design (e.g., sun/moon icons).  
   - Place the toggle in a prominent yet unobtrusive location within the Navbar.  

4. **Compatibility**:  
   - Ensure all UI elements adapt seamlessly to both themes, maintaining readability and aesthetics.

---

#### **Logo Redirect**  
1. **Clickable Logo**:  
   - Add the platform’s logo to the Navbar.  
   - Clicking the logo should navigate users to the homepage or dashboard.  

2. **Logo Placement**:  
   - Position the logo at the leftmost side of the Navbar for easy visibility and accessibility.  

3. **Responsive Design**:  
   - Ensure the logo resizes appropriately on different screen sizes without losing quality or usability.  

---

#### Theme Toggle Button  
- [ ] A theme toggle button is added to the Navbar.  
- [ ] The application updates dynamically when switching between light and dark themes.  
- [ ] The selected theme persists across sessions.  

#### Logo Redirect  
- [ ] A clickable logo is added to the Navbar.  
- [ ] Clicking the logo redirects users to the homepage or dashboard.  
- [ ] The logo is responsive and properly aligned in the Navbar.  

---

### **Priority:**  
- **Medium-High** (Enhances user experience and navigation).  

### **Time Estimate:**  
- **4-6 hours** (Design, development, and testing).  

---

Feel free to ask any queries

**Comment by Atharwa23** [comment]
Do i need to create a logo or assume the given text serves as a logo?

**Comment by PrathamJain2601** [comment]
> Do i need to create a logo or assume the given text serves as a logo?

for now add a random logo.png in public folder
