### ISSUE TITLE
Developing the chat component.

### ISSUE THREAD

**Issue by vanshdvn2505** [opencodeiiita/SkillSync-Frontend#28]
# Chat Component for Workspace Details Page  

## **Overview**  
This issue is for implementing the Chat Component in the Workspace Details Page. The Chat Component will allow workspace participants to engage in real-time messaging. It will cover 50% of the screen in the desktop view and adjust responsively for smaller screens.  

---

### **1. Message Display:**  
- Display a scrollable list of chat messages.  
- Each message should include:  
  - **Sender's Name/Avatar:** Display the sender's information.  
  - **Message Content:** Show the message text.  
  - **Timestamp:** Indicate when the message was sent.  

### **2. Message Input:**  
- Provide an input field for users to type their messages.  
- Include a "Send" button to post messages.  
- Disable the "Send" button if the input field is empty.  
- **Text Messaging:**  
  - A text field for typing messages.  
  - "Send" button to post messages.  
  - Disable "Send" button if the input field is empty.  
- **Resource Sharing:**  
  - A button to upload files or share resources (e.g., PDFs, images, or links).  
  - Show a preview of the file or resource being shared.  
  - Validate file types and sizes before uploading.  
- **Emojis:**  
  - An emoji picker to include emojis in the messages.  
- **Meeting Links:**  
  - An option to share scheduled or ongoing meeting links directly in the chat. 

### **3. Conditional Access:**  
- Show the chat interface **only** if the user is a member of the workspace.  
- If the user is not a member, display a prompt to join the workspace to access the chat.  

### **4. Real-Time Updates:**  
- Automatically update the chat messages when new ones are sent or received.  

### **5. Responsiveness:**  
- The Chat Component should occupy **50% of the screen** on larger devices.  
- On smaller screens, ensure the layout adjusts seamlessly (e.g., stacking below or above the workspace details pane).  

### **1. MessageList**  
- Displays the list of chat messages in a scrollable format.  
- Each message should highlight:  
  - Sender Name or Avatar.  
  - Message Content.  
  - Timestamp.  

### **2. MessageInput**  
- A fixed input bar for typing and sending messages.  
- Includes:  
  - Text input field for message content.  
  - "Send" button for submitting messages.  

---

## **Styling Guidelines**  
- **Screen Coverage:** The component should take 50% of the screen width on larger devices.  
- **Fixed Input Bar:** Ensure the input bar remains fixed at the bottom of the chat pane.  
- **Message Alignment:** Distinguish sent and received messages with different alignments or colors.  
- **Responsive Design:** Use media queries to handle smaller screens (e.g., stack below the workspace info).  

---

## **Expected Outcome**  
The Chat Component will provide a seamless and user-friendly real-time messaging experience for workspace participants, contributing to better collaboration.  

---

Time: 48hrs

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by ayush-patel1** [comment]
claim

**Comment by vanshdvn2505** [comment]
@Darkknight0125

Great work on the chat component! It’s coming along nicely, but I believe it can be improved further for a more polished user experience. Here’s an image for reference.

![Screenshot_2024-12-28-19-11-02-77_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/182bfc52-26e7-4006-8ee8-49e6b487194c)



For example:

1. Separate messages by date to make conversations easier to follow.


2. Add profile images next to each message for a more personal touch.


3. Use distinct colors to differentiate between the sender's and user's messages for better clarity.



These changes will enhance the overall usability and visual appeal. Let me know if you need any help or guidance while implementing them!

**Comment by vanshdvn2505** [comment]
Chat Component Added
