### ISSUE TITLE
Crafting the Sign-up Component

### ISSUE THREAD

**Issue by vanshdvn2505** [opencodeiiita/SkillSync-Frontend#3]
Develop the sign-in component, a vital element of our collaborative platform. Contributors are tasked with creating a user-friendly component that includes distinct fields for:
```json
"Name"
"Email Address"
"Username"
"Password"
```
These fields are essential for a seamless and secure registration process. Implement robust input validation for email formats and password strength to ensure security and usability. Ensure compatibility with various devices and browsers to guarantee a consistent experience for all users.

Once completed, submit a pull request with the code, and include relevant documentation for integration.

Time: 48 hours.

Please comment to claim the issue.

**Comment by Vardaan-02** [comment]
bhai mujhe assign karde 2 hour main likh dunga

**Comment by swarupn17** [comment]
I'm working on it.

**Comment by PrinkalDhingra** [comment]
@swarupn17 updates?
