### ISSUE TITLE
Crafting the Sign-In Component

### ISSUE THREAD

**Issue by vanshdvn2505** [opencodeiiita/SkillSync-Frontend#4]
Develop the sign-in component, a pivotal aspect of our collaborative platform.Craft a user-friendly component that seamlessly integrates a sign-in mechanism. This component should include the following distinct fields:

```json
"Username or Email"
"Password"
```

These fields are essential for a seamless and secure registration process. Implement robust input validation for email formats and password strength to ensure security and usability.

Additionally, contributors should focus on responsive design, ensuring compatibility with various devices and browsers to guarantee a consistent experience for all users.

Once completed, submit a pull request with the code, and include relevant documentation for integration.
Time: 48 hours.

Please comment to claim the issue.

**Comment by Snehalgupta-07** [comment]
claim

**Comment by Vardaan-02** [comment]
Bhai mujhe dede ye snehal ne vse bhi kaafi le rakhe hai 😭😭

**Comment by PrinkalDhingra** [comment]
@Snehalgupta-07 updates ?

**Comment by Snehalgupta-07** [comment]
> @Snehalgupta-07 updates ?
> 

Will do it by today
